### ISSUE TITLE
Use rolling app deployment feature in CF CLI

### ISSUE THREAD

**Issue by asudoh** [carbon-design-system/action-ibmcloud-cf#1]
https://docs.cloudfoundry.org/devguide/deploy-apps/rolling-deploy.html

**Comment by abdonrd** [comment]
Great, thanks @asudoh!

**Comment by asudoh** [comment]
Thanks @abdonrd - We found that IBM Cloud CLI doesn't seem to support the CF version with rolling deploy feature `v7`. So it's likely that we need to wait for a new IBM Cloud CLI version (though I may be wrong).

**Comment by abdonrd** [comment]
I see we can force a CF CLI update with: `ibmcloud cf install -v 7.1.0`
